### ISSUE TITLE
MongoDB使用してみてはどうか

### ISSUE THREAD

**Issue by maueki** [maueki/go_wiki#117]

**Comment by maueki** [comment]
MongoDBへの乗り換えを検討

## メリット
- スキーマレスなのでRDBMSでいうところの列追加のコスト(DBマイグレーション等)が低い
- 今回はタグや履歴管理があるのでリストの扱いがRDBMSより得意

## デメリット
- 慣れてない
- 複雑なクエリが苦手っぽい

**Comment by maueki** [comment]
取り敢えず機能ブランチで実験

**Comment by t7u** [comment]
:+1:
