### ISSUE TITLE
プロジェクトタグの実装

### ISSUE THREAD

**Issue by ghost** [maueki/go_wiki#145]

**Comment by maueki** [comment]
Pageは公開か非公開かの２通りのみもつ。
Pageはプロジェクトのリストを持つ。

非公開の場合はプロジェクトリストにあるプロジェクト参加者のみ閲覧可能
非公開かつプロジェクトリスト空の場合は、書いた本人のみ閲覧可能
公開の場合はリストにかかわらず全員閲覧可能

公開の場合でもプロジェクトの記事一覧等でプロジェクトリストには意味がある。

**Comment by maueki** [comment]
記事が複数のプロジェクトに属するのはユーザーごとのプロジェクト可視性と相まっていろいろ面倒が多そう。
とりあえず実装して使って問題点をだしていく方向か
