### ISSUE TITLE
Article, Historyに_idを設定する

### ISSUE THREAD

**Issue by maueki** [maueki/go_wiki#164]
Articleにbson.NewObjectIdでidを付け、
Historyに移す際にはそのidを引き継ぐ

**Comment by t7u** [comment]
これってなぜ必要なんでしたっけ？
Page.ID と Article.ID は同じでいいと思うのですが。

**Comment by maueki** [comment]
> Page.ID と Article.ID は同じでいいと思うのですが。

Article.IDはなくても良いが、History.IDはID指定して閲覧したいので必要かと
