### ISSUE TITLE
getUser*系関数はログインしているユーザーに依存しているので、関数名を変える

### ISSUE THREAD

**Issue by ghost** [maueki/go_wiki#184]
web.Cからセッション経由で取ってくるのか、引数で渡した値から取ってくるのかわかりづらい

**Comment by maueki** [comment]
`getUserById()` は `getUserFromDB()` からしか使われていないので統合して良さそう

**Comment by maueki** [comment]
`getUserById()` ほかから使うようになってますね。

`getUser()` を `getUserFromSession()` にrenameしますか
