### ISSUE TITLE
pageIdが16進の箇所は変数名等で明記する

### ISSUE THREAD

**Issue by ghost** [maueki/go_wiki#185]

**Comment by ghost** [comment]
久々にコードをみたら混乱してきました・・・

**Comment by maueki** [comment]
変数名じゃなくて型を明記すればよいのでは？

**Comment by t7u** [comment]
システムハンガリアン的なことをしようというのであれば反対。
型を明記 or 型を作成するべきでは。

**Comment by ghost** [comment]
DBは10進でページURLは16進なので名前で明記しないと混乱するということです、URLなので型は無理かと

**Comment by maueki** [comment]
`bson.ObjectIdHex()` は string型からbson.ObjectId型への変換ですな。

**Comment by maueki** [comment]
クローズします
