### ISSUE TITLE
履歴管理

### ISSUE THREAD

**Issue by maueki** [maueki/go_wiki#7]

**Comment by t7u** [comment]
blob で。

**Comment by t7u** [comment]
・圧縮するのはテキスト前提でよい
・表示時に圧縮されたものを展開するので展開速度が速いものがよい
・上の条件に一致するもので一番圧縮率が高いもの

**Comment by t7u** [comment]
これでいってみる。
http://www.slideshare.net/komiyaatsushi/dsirnlp-3-lz4

**Comment by maueki** [comment]
:+1:
